baseURL = "/"
languageCode = "en-us"
DefaultContentLanguage = "en"

title = "TravelgateX Documentation"
theme = "docdock"
#themesdir = "../.."

#GoogleAnalytics: "UA-106994170-2"

[outputs]
home = [ "HTML", "RSS", "JSON"]


[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
nofollowLinks = true

[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i> GraphQL Playground"
identifier = "ds"
url = "https://api.travelgatex.com"
weight = 10

#[[menu.shortcuts]]
#name = "<i class='fa fa-camera'></i> Showcases"
#url = "/showcase"
#weight = 11

#[[menu.shortcuts]]
#name = "<i class='fa fa-bookmark'></i> Hugo Documentation"
#identifier = "hugodoc"
#url = "https://gohugo.io/"
#weight = 20

#[[menu.shortcuts]]
#name = "<i class='fa fa-bullhorn'></i> Credits"
#url = "/credits"
#weight = 30


#Elade HOME

[params]

############## docdock params

#editURL = "https://github.com/vjeantet/hugo-theme-docdock/edit/master/exampleSite/content/"
editURL = "https://github.com/travelgateX/documentation-site/edit/master/content/"
showVisitedLinks = true # default is false
themeStyle = "flex" # "original" or "flex" # default "original"
#themeVariant = "blue" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
#disableHomeIcon = false # default is false
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false

discourseUrl = "http://community.travelgatex.com/"

############## docdock params


  #custom_css = ["css/blue.css"]

  # Meta
  author = "TravelgateX"
  description = "All you want and need to know about travelgateX state-of-the-art GraphQL APIs. Start your next travel project here."
  email = "info@travelgatex.com"
  # Navigation
  [params.navigation]
    brand = '<img src="images/xtg_logo.svg"/>'
    home = "Home"
    welcome = "About us"
    work = "Product"
    testimonials = "Testimonials"
    services = "Architecture"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # postpended links
    [[menu.prepend]]
     url = "https://api.travelgatex.com"
     name = "Playground <i title='Play &rarr;' class='icon-control-play'></i>"
     weight = 9
    [[menu.prepend]]
      url = "/getting-started/"
      name = "Get Started"
      weight = 10
    [[menu.prepend]]
     url = "https://slack.travelgatex.com/"
     name = '<img alt="slack travelgatex" src="https://slack.travelgatex.com/badge.svg" />'
     weight = 11
     hrefTargetBlank = true


  # Hero section
  [params.hero]
    title = "A travel API youâ€™ll &nbsp;&nbsp;<i title='love &#9825;' class='icon-heart'></i>"
    subtitle = "APIs that connect buyers and suppliers across the Travel Industry.<p>Welcome to TravelgateX, the worldâ€™s most advanced and disruptive GraphQL based Travel API.</p>"

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Getting Started"
    description = "The inner workings of our APIs. Search, book, retrieve stats, mapping hotels and much more."
    url = "getting-started/"
    button = "Go Get Started"
    icon = "icon-fire"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Learning GraphQL"
    description = "Get to know GraphQL, tutorials, resources. All you need to master the tech."
    url = "learning-graphql/"
    button = "Go Learn"
    icon = "icon-book-open"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "API Playground"
    description = "Don't take it from us, try our ready-made real life examples to see it for yourself."
    url = "https://api.travelgatex.com/"
    class = "external"
    button = "Go Play"
    icon = "icon-control-play"
    img = "img_10.jpg"
    target = "_blank"

  #[[params.intro.item]]
    #title = "Community"
    #description = "You're never alone. Join our growing community."
    #url = "http://discourse.travelgatex.com/"
    #button = "Join the Discussion"
    #icon = "icon-rocket"
    #img = "img_10.jpg"

  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"

  # Welcome section
  [params.welcome]
    enable = true
    title = "Connecting the dots"
    description = "With over 600 suppliers, and growing, our travel APIs focus on making sure you can integrate quickly and securely. Speed up integrations and search extensive supplier catalogues with record response time. Our APIs reduce time to market from 9 months to 2 weeks. See why OTA business developers say it is faster to use Travelgate than to do it themselves."

  # Work section
  [params.work]
    enable = true
    title = "Our products"
    description = "Weâ€™re true believers in the API first philosophy. Anything you can do on any of our sites and tools you can also do using the GraphQL API."
    footertext = 'APIs Made With &#9825; For Developers By Developers'

    [[params.work.row]]
      url = "https://www.travelgatex.com/products/hotelx"
      img = "hotelx.svg"
      alt = "HotelX"
      title = "HotelX"
      subtitle = "A single XML Integration to connect with more than 600 hotel product providers."

    [[params.work.row]]
      url = "https://www.travelgatex.com/products/channelx"
      img = "channelx.svg"
      alt = "channelX"
      title = "Channelx"
      subtitle = "With a single connection to our API you will receive the full portfolio of all the channels."

    [[params.work.row]]
      url = "https://www.travelgatex.com/products/flightsx"
      img = "flightx.svg"
      alt = "flightx"
      title = "FlightsX"
      subtitle = "A single XML Integration to connect with more than 30 flight providers."

    [[params.work.row]]
      url = "https://www.travelgatex.com/products/mappea"
      img = "mappea.svg"
      alt = "Mappea"
      title = "Mappea"
      subtitle = "Collaborative Assisted Mapping tool for hotels"

    [[params.work.row]]
      url = "https://www.travelgatex.com/products/inventory"
      img = "inventory.svg"
      alt = "Inventory"
      title = "Inventory"
      subtitle = "Inventory is the right solution for those clients willing to connect their offline product."


    [[params.work.row]]
      url = "https://www.travelgatex.com/products/speed"
      img = "speed.svg"
      alt = "Speed"
      title = "Speed"
      subtitle = "Speed is the smart cache solution designed entirely by TravegateX that manages to reduce the number of requests by up to 80%"


    [[params.work.row]]
      url = "https://www.travelgatex.com/products/insights"
      img = "insights.svg"
      alt = "Insights"
      title = "Insights"
      subtitle = "All the data stored in our system is available to you through our Business Intelligence solution"


    [[params.work.row]]
      url = "https://www.travelgatex.com/products/distribution"
      img = "distribution.svg"
      alt = "Distribution"
      title = "Distribution"
      subtitle = "We help you grow"


    [[params.work.row]]
      url = "https://www.travelgatex.com/products/stats"
      img = "stats.svg"
      alt = "Stats"
      title = "Stats"
      subtitle = "The Dashboard is the big data you need to evaluate your suppliers on result, response time and errors."




  # Testimonials section
  [params.testimonials]
    enable = false
    title = "Testimonials"
    description = "See what our Beta Testers &amp; Early Adopters have to say. Learn. Test. Decide."

    [[params.testimonials.item]]
      quote = "&ldquo;We've started working with the legacy API 4 years ago. When they've told us they were developing a new API we _had to be a part of it_. Our developers loved it, and best of all, we can now deliver all the integrations business requires us&rdquo;"
      person = 'Dani Martin, Architect <a href="http://www.guestincoming.com/" target="_blank">Guest Incoming</a> <span class="subtext">CTO</span>'
      img = "default-user.png"
      alt = "Dani Martin"

    [[params.testimonials.item]]
      quote = "&ldquo;I met these guys last year in Berlin and they've told us about the project, it was still at that stage, project only. But as soon as they've told me about their plans I knew they were on to something and I felt I _couldn't miss out_! It's by far the most advanced API I've seen in travel and in general, I'm impresses by the simplicity and speed of the API. Congrats guys!&rdquo;"
      person = 'Vitali, Senior Developer <a href="http://www.roomertravel.com/" target="_blank">Roomer Travel</a> <span class="subtext">CTO</span>'
      img = "default-user.png"
      alt = "Vitali"




  # Services section
  [params.services]
    enable = true
    title = "Architecture"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    # [[params.services.item]]
    #   title = "Brand &amp; Strategy"
    #   description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
    #   icon = "icon-anchor"
    #
    # [[params.services.item]]
    #   title = "Web &amp; Interface"
    #   description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
    #   icon = "icon-layers2"
    # [[params.services.item]]
    #   title = "Photo &amp; Video"
    #   description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
    #   icon = "icon-video2"
    #
    #   [[params.services.item]]
    #   title = "CMS &amp; eCommerce"
    #   description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
    #   icon = "icon-monitor"

  # About section
  [params.about]
    enable = false
    title = "About"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.about.item]]
      name = "Jean Smith"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Rob Smith"
      position = "Web Developer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

    [[params.about.item]]
      name = "Larry Ben"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]

  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "none"

    [[params.counters.item]]
      description = "Live Suppliers"
      icon = "icon-briefcase"
      from = 0
      to = 623
      interval = 50
      speed = 2000

    [[params.counters.item]]
      description = "Searches per Minute"
      icon = "icon-speedometer"
      from = 0
      to = 623456
      interval = 50
      speed = 2200

    [[params.counters.item]]
      description = "Bookings Per Day"
      icon = "icon-wallet"
      from = 0
      to = 23412
      interval = 50
      speed = 2000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 132
      interval = 50
      speed = 1000

  # Contact section
  [params.contact]
    enable = true
    map = true
    title = "Get in touch"
    description = "WeÂ´d love to hear from you! Drop us a line and we'll get back to you shortly."

    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Carrer Galileo Galilei, <br> ParcBit 07121 Palma, Illes Balears, Spain"],
        ["icon-phone", "(+34) 871 968 181"],
        ["icon-envelope", "info@travelgatex.com"],
        ["icon-globe", '<a href="http://www.travelgatex.com/" target="_blank">travelgatex.com</a>']
      ]

    name = "Full Name"
    email = "Email"
    phone = "Telephone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; <a title="TravelgateX" target="_blank" href="https://www.travelgatex.com/" style="color: white;font-weight: bold;">TravelgateX</a> 2018. All Rights Reserved. TravelgateX is made with &#9829; in the beaultiful  ðŸï¸ of Mallorca.'

# Related Content
[related]

  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

    [[related.indices]]
      name  = "tags"
      weight = 100
